// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.19.4
// source: addresspool_api.proto

package grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddressIdentity struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UUID       string `protobuf:"bytes,1,opt,name=UUID,proto3" json:"UUID,omitempty"`
	Address    string `protobuf:"bytes,5,opt,name=Address,proto3" json:"Address,omitempty"`
	WalletUUID string `protobuf:"bytes,6,opt,name=WalletUUID,proto3" json:"WalletUUID,omitempty"`
	IsReserved bool   `protobuf:"varint,7,opt,name=IsReserved,proto3" json:"IsReserved,omitempty"`
	ReservedAt uint64 `protobuf:"varint,8,opt,name=ReservedAt,proto3" json:"ReservedAt,omitempty"`
}

func (x *AddressIdentity) Reset() {
	*x = AddressIdentity{}
	if protoimpl.UnsafeEnabled {
		mi := &file_addresspool_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddressIdentity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddressIdentity) ProtoMessage() {}

func (x *AddressIdentity) ProtoReflect() protoreflect.Message {
	mi := &file_addresspool_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddressIdentity.ProtoReflect.Descriptor instead.
func (*AddressIdentity) Descriptor() ([]byte, []int) {
	return file_addresspool_api_proto_rawDescGZIP(), []int{0}
}

func (x *AddressIdentity) GetUUID() string {
	if x != nil {
		return x.UUID
	}
	return ""
}

func (x *AddressIdentity) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AddressIdentity) GetWalletUUID() string {
	if x != nil {
		return x.WalletUUID
	}
	return ""
}

func (x *AddressIdentity) GetIsReserved() bool {
	if x != nil {
		return x.IsReserved
	}
	return false
}

func (x *AddressIdentity) GetReservedAt() uint64 {
	if x != nil {
		return x.ReservedAt
	}
	return 0
}

type ReserveAddressRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	WalletUUID string `protobuf:"bytes,1,opt,name=WalletUUID,proto3" json:"WalletUUID,omitempty"`
}

func (x *ReserveAddressRequest) Reset() {
	*x = ReserveAddressRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_addresspool_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReserveAddressRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveAddressRequest) ProtoMessage() {}

func (x *ReserveAddressRequest) ProtoReflect() protoreflect.Message {
	mi := &file_addresspool_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveAddressRequest.ProtoReflect.Descriptor instead.
func (*ReserveAddressRequest) Descriptor() ([]byte, []int) {
	return file_addresspool_api_proto_rawDescGZIP(), []int{1}
}

func (x *ReserveAddressRequest) GetWalletUUID() string {
	if x != nil {
		return x.WalletUUID
	}
	return ""
}

type ReserveAddressResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address *AddressIdentity `protobuf:"bytes,1,opt,name=Address,proto3" json:"Address,omitempty"`
}

func (x *ReserveAddressResponse) Reset() {
	*x = ReserveAddressResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_addresspool_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReserveAddressResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveAddressResponse) ProtoMessage() {}

func (x *ReserveAddressResponse) ProtoReflect() protoreflect.Message {
	mi := &file_addresspool_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveAddressResponse.ProtoReflect.Descriptor instead.
func (*ReserveAddressResponse) Descriptor() ([]byte, []int) {
	return file_addresspool_api_proto_rawDescGZIP(), []int{2}
}

func (x *ReserveAddressResponse) GetAddress() *AddressIdentity {
	if x != nil {
		return x.Address
	}
	return nil
}

var File_addresspool_api_proto protoreflect.FileDescriptor

var file_addresspool_api_proto_rawDesc = []byte{
	0x0a, 0x15, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x70, 0x6f, 0x6f, 0x6c, 0x5f, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x50, 0x6f, 0x6f, 0x6c, 0x22, 0x9f, 0x01, 0x0a, 0x0f, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x55, 0x55, 0x49, 0x44,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x55, 0x55, 0x49, 0x44, 0x12, 0x18, 0x0a, 0x07,
	0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41,
	0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1e, 0x0a, 0x0a, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74,
	0x55, 0x55, 0x49, 0x44, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x57, 0x61, 0x6c, 0x6c,
	0x65, 0x74, 0x55, 0x55, 0x49, 0x44, 0x12, 0x1e, 0x0a, 0x0a, 0x49, 0x73, 0x52, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x49, 0x73, 0x52, 0x65,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x64, 0x41, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x52, 0x65, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x64, 0x41, 0x74, 0x22, 0x37, 0x0a, 0x15, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1e, 0x0a, 0x0a, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x55, 0x55, 0x49, 0x44, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x57, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x55, 0x55, 0x49, 0x44, 0x22,
	0x50, 0x0a, 0x16, 0x52, 0x65, 0x73, 0x65, 0x72, 0x76, 0x65, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x36, 0x0a, 0x07, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x61, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x50, 0x6f, 0x6f, 0x6c, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x42, 0x3f, 0x5a, 0x3d, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f,
	0x63, 0x72, 0x79, 0x70, 0x74, 0x6f, 0x77, 0x69, 0x7a, 0x65, 0x2d, 0x74, 0x65, 0x63, 0x68, 0x2f,
	0x62, 0x63, 0x2d, 0x77, 0x61, 0x6c, 0x6c, 0x65, 0x74, 0x2d, 0x62, 0x74, 0x63, 0x2d, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x70, 0x6f, 0x6f, 0x6c, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x67, 0x72,
	0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_addresspool_api_proto_rawDescOnce sync.Once
	file_addresspool_api_proto_rawDescData = file_addresspool_api_proto_rawDesc
)

func file_addresspool_api_proto_rawDescGZIP() []byte {
	file_addresspool_api_proto_rawDescOnce.Do(func() {
		file_addresspool_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_addresspool_api_proto_rawDescData)
	})
	return file_addresspool_api_proto_rawDescData
}

var file_addresspool_api_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_addresspool_api_proto_goTypes = []interface{}{
	(*AddressIdentity)(nil),        // 0: addressPool.AddressIdentity
	(*ReserveAddressRequest)(nil),  // 1: addressPool.ReserveAddressRequest
	(*ReserveAddressResponse)(nil), // 2: addressPool.ReserveAddressResponse
}
var file_addresspool_api_proto_depIdxs = []int32{
	0, // 0: addressPool.ReserveAddressResponse.Address:type_name -> addressPool.AddressIdentity
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_addresspool_api_proto_init() }
func file_addresspool_api_proto_init() {
	if File_addresspool_api_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_addresspool_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddressIdentity); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_addresspool_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReserveAddressRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_addresspool_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReserveAddressResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_addresspool_api_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_addresspool_api_proto_goTypes,
		DependencyIndexes: file_addresspool_api_proto_depIdxs,
		MessageInfos:      file_addresspool_api_proto_msgTypes,
	}.Build()
	File_addresspool_api_proto = out.File
	file_addresspool_api_proto_rawDesc = nil
	file_addresspool_api_proto_goTypes = nil
	file_addresspool_api_proto_depIdxs = nil
}
